document.write('                    style="box-shadow: 0 0 10px rgba(0,0,0,0.38)" src="" />')
document.write('</div>')
document.write('    <footer class="footer">')
document.write('        <div class="footer-line">Powered By <a href="https://github.com/arbeiterklassen/Soyorin-Work" target="_blank">Soyorin.Work - '+"AKlassen's Blogs</a> 浙ICP备1145141919810号• © 2022</div>")
document.write('    </footer>')
document.write('    <script type="text/javascript" src="../js/jquery-3.4.1.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/sweetalert.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/pace.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/base.js"></script>')
document.write('    <script type="text/javascript" src="../js/d-audio.js"></script>')
document.write('    <script type="text/javascript" src="../js/myPagination.js"></script>')
document.write('    <script type="text/javascript" src="../js/vditor.min.js"></script>')
document.write('    <script type="text/javascript" src="../js/article-detail.js"></script>')
document.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>')
document.write('    <script src="https://cdn.staticfile.org/layer/3.1.1/layer.js"></script>')
document.write('    <script>document.body.oncopy = function() {layer.msg("复制成功,若要转载请务必保留原文链接<br>并遵守 (CC)-BY-NC-SA 协议");};</script>')
document.write('    <script type="text/x-mathjax-config">')
document.write('    MathJax.Hub.Config({')
document.write('        showProcessingMessages: false, //关闭js加载过程信息')
document.write('        messageStyle: "none", //不显示信息')
document.write('        extensions: ["tex2jax.js"],')
document.write('        jax: ["input/TeX", "output/HTML-CSS"],')
document.write('        tex2jax: {')
document.write('            inlineMath:  [ ["$", "$"] ], //行内公式选择$')
document.write('            displayMath: [ ["$$","$$"] ], //段内公式选择$$')
document.write('            skipTags: ["script", "noscript", "style", "textarea", "pre","code"","a"], //避开某些标签')
document.write('            ignoreClass:"comment-content" //避开含该Class的标签')
document.write('        },')
document.write('        "HTML-CSS": {')
document.write('            availableFonts: ["STIX","TeX"], //可选字体')
document.write('            showMathMenu: false //关闭右击菜单显示')
document.write('        }')
document.write('    });')
document.write('    MathJax.Hub.Queue(["Typeset",MathJax.Hub]);')
document.write('    </script>')
document.write('    <script type="text/javascript" defer>')
document.write('    //图片懒加载')
document.write('    onst lazyImage = new LazyImage(".lazy-image");')
document.write('    </script>')